
Application:
  External_Files_Names:
    Identity_Provider:
      certificate: ./src/main/resources/idp/saml.pre-producao.cer
    Service_Provider:
      private_key: ./src/main/resources/sp/private_key.der
      certificate: ./src/main/resources/sp/certificate.crt
  
  Attributes:
    Identity_Provider:
      AttributeItems:
        - name: Identificação Civil
          attr: http://interop.gov.pt/MDC/Cidadao/NIC
          group: Cartão de Cidadão
        - name: Nome Próprio
          attr: http://interop.gov.pt/MDC/Cidadao/NomeProprio
          group: Cartão de Cidadão
        - name: Apelido
          attr: http://interop.gov.pt/MDC/Cidadao/NomeApelido
          group: Cartão de Cidadão
        - name: Data de Nascimento
          attr: http://interop.gov.pt/MDC/Cidadao/DataNascimento
          group: Cartão de Cidadão
        - name: Nome Completo
          attr: http://interop.gov.pt/MDC/Cidadao/NomeCompleto
          group: Cartão de Cidadão

    Service_Provider:
      Login_request:
        - name: Identificação Civil
        - name: Nome Completo
        
        
          
    